apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-zhilabs
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-web
  template:
    metadata:
      labels:
        app: mi-web
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: default
spec:
  selector:
    app: mi-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
